### ISSUE TITLE
Auth configuration doesn't work

### ISSUE THREAD

**Issue by krisu5** [YunoHost-Apps/rss-bridge_ynh#27]
When enabling auth from config.ini.php file (https://github.com/RSS-Bridge/rss-bridge/wiki/Custom-Configuration#authentication), it doesn't accept name / pass.

---

EDIT: **Solution (in my case)** is to use same password as user account.

**Comment by mediaformat** [comment]
I just tried this, and got it to work! 
```
Debian 10
YunoHost 4.0.8 (stable).
rss-bridge 2020-02-26~ynh2
```

**Comment by alien2003** [comment]
Doesn't work for me too

**Comment by lapineige** [comment]
Is this still an issue ?

**Comment by krisu5** [comment]
> 
> 
> Is this still an issue ?

It is.

```
Debian 10
YunoHost 4.1.7.4
2020-11-10~ynh1
```

**Comment by lapineige** [comment]
Can you try to upgrade to lastest version, just in case ?

**Comment by krisu5** [comment]
> Can you try to upgrade to lastest version, just in case ?

YunoHost says that everything is up to date. Is there some beta version?

**Comment by lapineige** [comment]
My bad, I confused your version with the one in a message above.

I have no idea about what's going wrong, maybe there is some log that you can share to help us investigate that issue ?

> it doesn't accept name / pass

What do you mean by that ? It doesn't prompt for a password ?

**Comment by krisu5** [comment]
> > it doesn't accept name / pass
> 
> What do you mean by that ? It doesn't prompt for a password ?

No, it does prompt. However, it doesn't accept the login and password I added, even though they are correct (I have copypasted the login and password to login prompt, so I'm sure).

It just asks login info again and again, until you cancel it and shows the "unauthorized" error page.

**Comment by krisu5** [comment]
Okay, I finally figured it out.

It's browser-based issue, I can login with Brave and clean Firefox. I have some about:config tweaks in my Firefox setup that I have enabled, most likely culprit is `privacy.firstparty.isolate`.

Sorry for wasting your time, I would have never guessed this would be browser issue :/

**Comment by lapineige** [comment]
I tried, I can reproduce that issue, even with empty login and password.
I couldn't find any relevant log…

edit:
> It's browser-based issue, I can login with Brave and clean Firefox. I have some about:config tweaks / addons in my Firefox setup that I have enabled, I have to see what would it be.

If you find out, I'm curious to know :)
(maybe a referrer/redirect or cookie setting ?)

> Sorry for wasting your time, I would have never guessed this would be browser issue :/

No worries, you couldn't know, and this solved your issue, then that's perfect :)

**Comment by lapineige** [comment]
(Can you close the issue ? :)

**Comment by krisu5** [comment]
> (Can you close the issue ? :)

Well, I spoked too soon, LOL.

Issue **wasn't** a browser, it seems that when you're logged in on YunoHost SSO and tried to go to RSS-Bridge then, issue happens again.

But you can login in RSS-bridge if you are logged out of YunoHost SSO.

**Comment by lapineige** [comment]
Ooooook that's interesting… so maybe there is a conflict between Yunohost SSO and Shaarli authentication mechanism… :thinking:
Did you try with your Yunohost account credential (without logging into SSO) ?

**Comment by krisu5** [comment]
> Ooooook that's interesting… so maybe there is a conflict between Yunohost SSO and Shaarli authentication mechanism… 🤔
> Did you try with your Yunohost account credential (without logging into SSO) ?

Nope, I have tested this with credentials in config.ini.php that are totally different then my YunoHost user/pass.

**Comment by lapineige** [comment]
Can you try ?

**Comment by krisu5** [comment]
> Can you try ?

Sorry, I forgot.

It doesn't ask log in and succesfully access the page, if user/pass is same then YunoHost user/pass.

**Comment by lapineige** [comment]
So that option forces authentication, but with yunohost account… good to know.

**Comment by mediaformat** [comment]
My config uses an existing YunoHost-SSO username, but with a different password.
