### ISSUE TITLE
erreur lors de l'install "variable USER unbound"

### ISSUE THREAD

**Issue by ckiw** [YunoHost-Apps/rss-bridge_ynh#4]
salut

Tout d'abord, merci à vous qui faites en sorte que ce projet soit compatible avec ynh :)

Ensuite, j'ai rencontré une erreur lors de l'install via l'interface d'admin web, j'ai testé avec la ligne de commande et pas de soucis.

L'erreur était ligne 51 de common.sh "variable USER unbound"

J'avais mon disque plein lors de la première fois que j'ai testé l'install ce qui a ptet fait foirer des trucs.

Bref merci à vous. J'espère que mon petit commentaire vous aidera si d'autres users rencontrent des soucis :)

**Comment by JimboJoe** [comment]
Salut,
Désolé pour le délai, je n'avais pas vu passer ce rapport...
Je ne reproduis pas le problème de mon côté. Pourrais-tu STP lancer l'installation en ligne de commande comme ceci et partager tes logs?
```
yunohost app install rss-bridge --verbose
```
Merci !

**Comment by ckiw** [comment]
Salut, 

Merci de ta réponse, comme précisé, en ligne de commande c'est passé sans soucis donc je peux pas reproduire.

Tant pis, au moins si quelqu'un a le même soucis il pourra trouver un workaround ici ;)

**Comment by JimboJoe** [comment]
En fait, le problème est reproductible systématiquement depuis l'interface d'administration...

**Comment by lapineige** [comment]
Mais pas en ligne de commande ?

**Comment by JimboJoe** [comment]
Non, c'est bizarre... la variable d'environnement $USER n'est pas positionnée quand c'est lancé via l'interface web.
En même temps, il faudrait ré-écrire le package mais je n'en ai vraiment pas le temps en ce moment... donc je fais au plus rapide :wink:

**Comment by lapineige** [comment]
Merci du correctif :)
