### ISSUE TITLE
Pull from master please

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/rss-bridge_ynh#52]
They rarely have releases. Even their official instance https://rss-bridge.org/bridge01/ pulls from the master (see bottom of the page):
![2023-02-07_22-20](https://user-images.githubusercontent.com/38043315/217368380-37866758-0fe4-48d7-9a79-7251aace84ec.png)
The YNH package is not updated in almost a year. Things do not work well.

Please use the master and the perhaps the latest commit. If you switch to master I can keep it updated with the latest commits.

**Comment by lapineige** [comment]
The easiest way to update the package would be to create that release archive ourselves. But that's also the most painful to maintain afterwards.
About switching to master (via git I guess), that would be a great improvement, but I'm not knowledgeable enough to do it in the limited time I have for now.

Any help would be very appreciated, I can guide you if someone is wiling to try :)

**Comment by tio-trom** [comment]
Maybe looking at how Friendica it is done https://github.com/YunoHost-Apps/friendica_ynh/blob/master/scripts/_common.sh can be helpful....

I'll tag @mr-eshua if he has any time...but probably he won't.

**Comment by mr-eshua** [comment]
@lapineige @tio-trom I will try to take a look this weekend 😉

**Comment by mr-eshua** [comment]
Hey guys, apologies, I could not get to it in reasonable time, unfortunately. I have left [a comment](https://github.com/YunoHost-Apps/rss-bridge_ynh/pull/54/files#r1143977332) in #54, but @tio-trom already knows what he is doing. Seems like an easiest and, in general, better approach to update with the more recent versions from the upstream.

The option with cloning an entire git repo which I used with the friendica package is considered as less secure and does not pass the ynh testing sometimes, so my latest PR was not even merged because of that.

Anyway, I will be around if you would need any help.

**Comment by lapineige** [comment]
Thanks anyway :)

**Comment by lapineige** [comment]
Progress has been made, we now know that we can use any commit :)
The issue will be to decide which one…
And the version naming, I would suggest to use the date of the commit.

#58 for your information an upgrade was recently done thanks to your work :)

**Comment by tio-trom** [comment]
> Progress has been made, we now know that we can use any commit :) The issue will be to decide which one… And the version naming, I would suggest to use the date of the commit.
> 
> #58 for your information an upgrade was recently done thanks to your work :)

Great!

**Comment by tio-trom** [comment]
By the way I see that RSS Bridge prepares a new release https://github.com/RSS-Bridge/rss-bridge/commit/9bb04ba848e2449a7c65d4c54b53130484b9f442 ....

**Comment by lapineige** [comment]
Oh you mean the one already released https://github.com/RSS-Bridge/rss-bridge/releases/tag/2023-03-22 and merged #58 into testing then as the main package version #60 ? 😉 :D

**Comment by tio-trom** [comment]
Hm ok yea I thought you did it via commits because as we talked they didn't release in almost a year. I didn't see you used the release.

**Comment by lapineige** [comment]
There is a recent release, I always prefer to use that (it is supposed to be stable), and it's easy in that case :)

My big question with commits number is "when to decide it's a stable/safe version" ?
I don't use it that much to I can't really test.

**Comment by tio-trom** [comment]
No I 100% agree!
