### ISSUE TITLE
After the latest update many feeds explode with errors

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/rss-bridge_ynh#61]
So I run this website https://tromnews.com that pulls rss feeds from youtube and reddit mainly. And most of them are exploding with "Bridge returned error 0! (19443)" and other such errors. This did not happened before. I cannot find a fix. I had to revert back. idk what's the problem but maybe the current RSS Bridge release is buggy. Anyone else experiences this?

**Comment by lapineige** [comment]
Is that still the case ?

**Comment by tio-trom** [comment]
I will test it the following days and update this issue.

**Comment by tio-trom** [comment]
Ok I got some time to test. It seems that all works now except this https://github.com/RSS-Bridge/rss-bridge/issues/3623 but probably an upstream issue.
