### ISSUE TITLE
"mbstring" extension not loaded

### ISSUE THREAD

**Issue by bugsysop** [YunoHost-Apps/rss-bridge_ynh#9]
When trying to load RSS-Bridge page:
"mbstring" extension not loaded. Please check "php.ini"

Yunohost version: 3.5.2.2 (stable).

**Comment by JimboJoe** [comment]
Can you please try to install mbstring via `apt install php-mbstring`?

**Comment by bugsysop** [comment]
Done!
After askef for: `php-simplexml` and `php-curl`
And now Bridge is running...

Is the installer supposed to install also PHP modules?

**Comment by JimboJoe** [comment]
Yes, absolutely, I will have to add the installation of these dependencies. These lacking dependencies can be missed if other YunoHost applications already installed them.

**Comment by bugsysop** [comment]
Same missing dependencies also blocked Rainloop Webmail install.
Thanks for the YNH port of RSS-Bridge, and for your prompt response.
Have a nice day

**Comment by bugsysop** [comment]
https://github.com/YunoHost/issues/issues/1320

**Comment by mediaformat** [comment]
Just installed, got the same error.

Shouldn’t the install script do the ‘apt’ command?

**Comment by bugsysop** [comment]
You can see here for a (temporary) solution
https://github.com/YunoHost/issues/issues/1320#issuecomment-491520221

Read the ful thread ;-)
